language: java
jdk: openjdk12
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - ./gradlew assemble
  - ./gradlew check
  - ./gradlew run & sleep 5 && npx newman run docs/TODOOSE.postman_collection.json && kill %1
